insert into movie_idea(version, user_name, movie_title, genre, date_added) values (0, 'john_doe123', 'Once upon a time in Lapinlahti', 'Comedy', '2025-04-12');
insert into movie_idea(version, user_name, movie_title, genre, date_added) values (0, 'anna_korhonen88', 'The Night of the Horror', 'Horror', '2025-04-10');
insert into movie_idea(version, user_name, movie_title, genre, date_added) values (0, 'peter_smith2025', 'A Comedy of Errors', 'Comedy', '2025-04-09');
insert into movie_idea(version, user_name, movie_title, genre, date_added) values (0, 'susan_lee321', 'Drama in the Rain', 'Drama', '2025-04-05');
insert into movie_idea(version, user_name, movie_title, genre, date_added) values (0, 'michael_brown567', 'Through the Silent Night', 'Thriller', '2025-04-04');
insert into movie_idea(version, user_name, movie_title, genre, date_added) values (0, 'emma_tuomi456', 'The Last Summer in Lestijärvi', 'Drama', '2025-04-01');
insert into movie_idea(version, user_name, movie_title, genre, date_added) values (0, 'luke_williams222', 'Comedy in the Midnight Sun', 'Comedy', '2025-03-28');
insert into movie_idea(version, user_name, movie_title, genre, date_added) values (0, 'julia_martin789', 'Under the Finnish Moon', 'Romance', '2025-03-25');
insert into movie_idea(version, user_name, movie_title, genre, date_added) values (0, 'daniel_lee321', 'The Whispering Pines', 'Thriller', '2025-03-22');
insert into movie_idea(version, user_name, movie_title, genre, date_added) values (0, 'anna_smith500', 'Escape from the Snowstorm', 'Action', '2025-03-19');
insert into movie_idea(version, user_name, movie_title, genre, date_added) values (0, 'olivia_johnson711', 'Frozen Tears of the North', 'Drama', '2025-03-18');
insert into movie_idea(version, user_name, movie_title, genre, date_added) values (0, 'markus_karhu999', 'Silence Before the Storm', 'Horror', '2025-03-15');
insert into movie_idea(version, user_name, movie_title, genre, date_added) values (0, 'sophia_brown222', 'Journey Through the Hood', 'Adventure', '2025-03-10');
insert into movie_idea(version, user_name, movie_title, genre, date_added) values (0, 'noah_williams333', 'City of Shadows', 'Thriller', '2025-03-05');
insert into movie_idea(version, user_name, movie_title, genre, date_added) values (0, 'laura_niemi555', 'Helsinki Express', 'Action', '2025-03-02');
insert into movie_idea(version, user_name, movie_title, genre, date_added) values (0, 'benjamin_white444', 'Lights Over the Lake', 'Romance', '2025-02-28');
insert into movie_idea(version, user_name, movie_title, genre, date_added) values (0, 'eliza_jones666', 'Beyond the Northern Lights', 'Documentary', '2025-02-26');
insert into movie_idea(version, user_name, movie_title, genre, date_added) values (0, 'alexander_king777', 'Midnight Escape from Lofoten', 'Action', '2025-02-22');
insert into movie_idea(version, user_name, movie_title, genre, date_added) values (0, 'mia_patterson888', 'The Frozen World', 'Adventure', '2025-02-20');
insert into movie_idea(version, user_name, movie_title, genre, date_added) values (0, 'andrew_lee555', 'A Stranger in Lapland', 'Mystery', '2025-02-17');
insert into movie_idea(version, user_name, movie_title, genre, date_added) values (0, 'lucas_davis444', 'The Final Downcount', 'Action', '2025-02-14');
insert into movie_idea(version, user_name, movie_title, genre, date_added) values (0, 'devilSlayerD50', 'Abomination of the Toxic Wastes', 'Romance', '2024-11-19');
insert into application_user (version, username, avatarname, hashed_password) values (0,'user','FunnyJollyTimes','$2a$10$xdbKoM48VySZqVSU/cSlVeJn0Z04XCZ7KZBjUBC00eKo5uLswyOpe');
insert into user_roles (user_id, roles) values (1, 'USER');
insert into application_user (version, username, avatarname, hashed_password) values (0,'admin','EmmaTheGemma','$2a$10$jpLNVNeA7Ar/ZQ2DKbKCm.MuT2ESe.Qop96jipKMq7RaUgCoQedV.');
insert into user_roles (user_id, roles) values (2, 'USER');
insert into user_roles (user_id, roles) values (2, 'ADMIN');
